// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaolwmbknfwpnkrsqrxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hb2x3bWJrbmZ3cG5rcnNxcnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Nzc5MTMsImV4cCI6MjA2NDU1MzkxM30.rAUSze48pqW4QE4R2ZGLARPGGdY3mQIWsNQArpuH1qM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);